### ISSUE TITLE
A error for Rocket.Translation

### ISSUE THREAD

**Issue by kulkaGM** [archie426/RocketModToOpenMod#2]
_Unhadlel exception. System.IO.FileNotFoundException: Could not find file 'U3DS\Servers\ServerName\Rocket\Rocket.Translations.en.xml'_

Correct name is 'Rocket.en.translation.xml'.

**Comment by hiilikewiki** [comment]
I'm sure I remember checking the file names, I think in future I will probably do a much more thorough search for the Rocket data files in the folder

**Comment by kulkaGM** [comment]
If it was it right I wouldn't write it what is messed up.
But it doesn't matter now cuz i think we discuss it on the Discord.
